### ISSUE TITLE
incompatible with route translator gem ?

### ISSUE THREAD

**Issue by optimum-dulopin** [tolk/tolk#113]
I have this error :

ArgumentError: Invalid route name, already in use: 'tolk' 
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
~/.rvm/gems/ruby-2.2.2@myapp/gems/actionpack-4.1.12/lib/action_dispatch/routing/route_set.rb:444:in `add_route'
~/.rvm/gems/ruby-2.2.2@myapp/gems/route_translator-4.0.0/lib/route_translator/extensions/mapper.rb:37:in `add_route'
~/.rvm/gems/ruby-2.2.2@myapp/gems/actionpack-4.1.12/lib/action_dispatch/routing/mapper.rb:1472:in `decomposed_match'
~/.rvm/gems/ruby-2.2.2@myapp/gems/actionpack-4.1.12/lib/action_dispatch/routing/mapper.rb:1453:in `block in match'
~/.rvm/gems/ruby-2.2.2@myapp/gems/actionpack-4.1.12/lib/action_dispatch/routing/mapper.rb:1443:in `each'
~/.rvm/gems/ruby-2.2.2@myapp/gems/actionpack-4.1.12/lib/action_dispatch/routing/mapper.rb:1443:in `match'
~/.rvm/gems/ruby-2.2.2@myapp/gems/actionpack-4.1.12/lib/action_dispatch/routing/mapper.rb:536:in `mount'
~/Documents/rails/gancx/myapp/config/routes.rb:6:in `block in <top (required)>'

**Comment by optimum-dulopin** [comment]
i found the reason, dont know why but 

  mount Tolk::Engine => '/tolk', :as => 'tolk'

was added twice in my routes file
