### ISSUE TITLE
Tolk with protected_attributes gem

### ISSUE THREAD

**Issue by ilkerinanc** [tolk/tolk#68]
Hi,

I'm using Rails 4 and Ruby 2 and I'm also using `protected_attributes` gem in my Gemfile. That causes me the following error upon running `rake tolk:sync` :

```
NoMethodError: undefined method `to_sym' for nil:NilClass
/Users/ilker/.rvm/gems/ruby-2.0.0-p481/gems/tolk-1.5.1/lib/tolk/sync.rb:14:in `load_translations'
/Users/ilker/.rvm/gems/ruby-2.0.0-p481/gems/tolk-1.5.1/lib/tolk/sync.rb:9:in `sync!'
/Users/ilker/.rvm/gems/ruby-2.0.0-p481/gems/tolk-1.5.1/lib/tasks/tolk_tasks.rake:19:in `block (2 levels) in <top (required)>'
/Users/ilker/.rvm/gems/ruby-2.0.0-p481/gems/bugsnag-2.1.0/lib/bugsnag/rake.rb:34:in `block in bugsnag_define_task'
/Users/ilker/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
/Users/ilker/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
```

When I further dig down and run the `Tolk::Locale.sync!` in console I get the following:

```
Tolk::Locale Load (1.2ms)  SELECT "tolk_locales".* FROM "tolk_locales" WHERE "tolk_locales"."name" = 'en' LIMIT 1
WARNING: Can't mass-assign protected attributes for Tolk::Locale: name

   (0.2ms)  BEGIN
  Tolk::Locale Exists (0.4ms)  SELECT 1 AS one FROM "tolk_locales" WHERE "tolk_locales"."name" IS NULL LIMIT 1
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
   (0.2ms)  ROLLBACK
NoMethodError: undefined method `to_sym' for nil:NilClass
    from /Users/ilker/.rvm/gems/ruby-2.0.0-p481/gems/tolk-1.5.1/lib/tolk/sync.rb:14:in `load_translations'
    from /Users/ilker/.rvm/gems/ruby-2.0.0-p481/gems/tolk-1.5.1/lib/tolk/sync.rb:9:in `sync!'
    from (irb):1
    from /Users/ilker/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.0.1/lib/rails/commands/console.rb:90:in `start'
    from /Users/ilker/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.0.1/lib/rails/commands/console.rb:9:in `start'
    from /Users/ilker/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.0.1/lib/rails/commands.rb:62:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

Any ideas how to work around?

**Comment by wpp** [comment]
I just ran into something similar, for a quick work-around I added the following to an initializer:

    Tolk::Locale.send(:attr_accessible, :name)
    Tolk::Phrase.send(:attr_accessible, :key)

    ["phrase", "phrase_id", "locale", "locale_id", "text", "previous_text", "primary_updated"].each do |attr|
      Tolk::Translation.send(:attr_accessible, attr)
    end

I'm using 

- tolk (1.9.2)
- protected_attributes (1.0.8)
